---
- name: Ansible_ssh_conf_4_CentOS # 참고로 ubuntu는 이 설정이 필요없음.
  hosts: localhost
  gather_facts: no

  tasks:
    - name: PasswordAuthentication change from no to yes
      replace: 
        dest: /etc/ssh/sshd_config
        regexp: 'PasswordAuthentication no'
        replace: 'PasswordAuthentication yes'
        backup: yes
    - name: sshd restart to apply 'PasswordAuthentication'
      service: 
        name: sshd
        state: restarted