Vagrant_API_Version = '2'

Vagrant.configure(Vagrant_API_Version) do |config|
  
  # Ansible-node01
  config.vm.define:'ansible-node01' do |cfg| 
    cfg.vm.box='centos/7'  
    cfg.vm.provider:virtualbox  do |vb|  
      vb.name = 'Ansible-Node01'
      vb.customize ['modifyvm', :id, '--cpus', 1] # cpu 사용량 수정
      vb.customize ['modifyvm', :id, '--memory', 512] # 메모리 사용량 수정 
    end
    cfg.vm.host_name='ansible-node01' 
    cfg.vm.synced_folder ".", "/vagrant", disabled: true 
    cfg.vm.network 'public_network', ip: '172.30.1.101' 
    cfg.vm.network 'forwarded_port', guest: 22, host:17211, auto_currect:false, id:'ssh'
    cfg.vm.provision 'shell', path: 'bash_ssh_conf_4_CentOS.sh'
  end

    # Ansible-node02
    config.vm.define:'ansible-node02' do |cfg| 
      cfg.vm.box='centos/7'  
      cfg.vm.provider:virtualbox  do |vb|  
        vb.name = 'Ansible-Node02'
        vb.customize ['modifyvm', :id, '--cpus', 1] # cpu 사용량 수정
        vb.customize ['modifyvm', :id, '--memory', 512] # 메모리 사용량 수정 
      end
      cfg.vm.host_name='ansible-node02' 
      cfg.vm.synced_folder ".", "/vagrant", disabled: true 
      cfg.vm.network 'public_network', ip: '172.30.1.102' 
      cfg.vm.network 'forwarded_port', guest: 22, host:17212, auto_currect:false, id:'ssh'
      cfg.vm.provision 'shell', path: 'bash_ssh_conf_4_CentOS.sh'
    end

    # Ansible-server
  config.vm.define:'ansible-server' do |cfg|  # vagrant ssh 접속시 불러주는 호스트명
    # define 밑으로 들어가기 
    cfg.vm.box='centos/7'   # 사용할 이미지 
    cfg.vm.provider:virtualbox  do |vb|   # virtualbox를 사용할 것이므로 
      vb.name = 'Ansible-Server'  # virtual box에서 사용될 이름 
    end
    cfg.vm.host_name='ansible-server'  # 설치하는 가상머신에서 보이는 호스트네임 
    cfg.vm.synced_folder ".", "/vagrant", disabled: true  # 파일 마운트하지 않음 
    cfg.vm.network 'public_network', ip: '172.30.1.100'  # public_network 설정시 bridge로 설정된다. 
    cfg.vm.network 'forwarded_port', guest: 22, host:17200, auto_currect:false, id:'ssh'
    # 호스트에서 19210으로 접속시 vm의 22번포트로 포워딩 
    cfg.vm.provision 'shell', path: 'bootstrap.sh' # path는 해당 파일을 전송하고 실행  
    cfg.vm.provision 'file', source: 'Ansible_env_ready.yaml', destination: 'Ansible_env_ready.yaml' # file은 전송만 
    cfg.vm.provision 'shell', inline: 'ansible-playbook Ansible_env_ready.yaml' # inline은 실행만
    cfg.vm.provision 'shell', path: 'add_ssh_auth.sh', privileged: false # root권한이 아닌  vagrant 권한을 사용하겠다. 
    cfg.vm.provision 'file', source: 'Ansible_ssh_conf_4_CentOS.yml', destination: 'Ansible_ssh_conf_4_CentOS.yml'
    cfg.vm.provision 'shell', inline: 'ansible-playbook Ansible_ssh_conf_4_CentOS.yml'
  end
end

