---

- name: Setup for nfs server
  gather_facts: no
  hosts: localhost

  tasks:
  - name: make nfs_shared directory
    file: 
      path: /home/vagrant/nfs_shared
      state: directory
      mode: 0777
  
  - name: configure /etc/exports
    become: yes
    lineinfile: 
      path: /etc/exports
      line: /home/vagrant/nfs_shared/ 172.30.1.0/24(rw,sync)
  
  - name: nfs service restart
    become: yes
    service:
      name: nfs
      state: restarted 



- name: Setup for nfs clients
  hosts: centOS:ubuntu
  gather_facts: no

  tasks:
  - name: make nfs_client directory
    file: 
      path: /home/vagrant/nfs
      state: directory

  - name: mount directory 
    become: yes
    mount: 
      name: /home/vagrant/nfs 
      src: 172.30.1.100:/home/vagrant/nfs_shared
      fstype: nfs
      opts: nfsvers=3
      state: mounted 
