Vagrant.configure("2") do |config|
  config.vm.define: 'ansible-server' do |cfg|  # vagrant ssh 접속시 불러주는 호스트명
    # define 밑으로 들어가기 
    cfg.vm.box = 'centos/7'   # 사용할 이미지 
    cfg.vm.provider:virtualbox  do |vb|   # virtualbox를 사용할 것이므로 
      vb.name-'Ansible-Server'  # virtual box에서 사용될 이름 
    end
    cfg.vm.host_name='ansible-server'  # 설치하는 가상머신에서 보이는 호스트네임 
    cfg.vm-synced_folder '.', '/vagrant', disabled: true  # 파일 마운트하지 않음 
    cfg.vm.network 'public_network', ip: '192.168.1.10'  # public_network 설정시 bridge로 설정된다. 
    cfg.vm.network 'forward_port', guest: 22, host:19210, auto_currect:false, id:'ssh'
    # ssh 접속을 위해 게스트는 22번 호스트는 19210번을 사용  
    cfg.vm.provision 'shell', path: 'bootstrap.sh' # 앤서블 설치를 위한 스크립트 
  end
end
